version: '{branch}.{build}'

image: Ubuntu2204

install:
  - nvm use 20
  - npm install

build_script:
  - npm run eslint
  - npm run build

test_script:
  - npm run test:appveyor

on_finish:
  - sh: curl -F 'file=@junit.xml' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"