version: 2
jobs:
  build:
    
    branches:
      only:
        - dev

    docker:
      - image: circleci/node:12.14

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build